apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-fleet
  project: giri
spec:
  base:
    name: minimal
    version: 2.7.0
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  placement:
    fleetValues:
    - rafay
  type: custom
  version: v2
