apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: dependency
  project: giri
spec:
  base:
    name: minimal
    version: 2.7.0
  componentsCriticality:
  - name: xwing-fail
  customAddons:
  - name: xwing-fail2
    version: v1
  - dependsOn:
    - xwing-fail2
    name: xwing-fail
    version: v1
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
