apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: git-custom
  project: giri
spec:
  base:
    name: default-aks
    version: 2.7.0
  componentsCriticality:
  - name: redis1
  customAddons:
  - name: xwing-fail
    version: v1
  - name: redis1
    version: redis-v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: version2-custom
