apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: krishna-bp
  project: giri
spec:
  base:
    name: minimal
    version: 2.7.0
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
