apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: cb
  project: giri-may
spec:
  base:
    name: np-gb
    version: version1
  componentsCriticality:
  - name: network-policy
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v133
