apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: cbpmay
  project: giri-may
spec:
  base:
    name: gbpmay
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
