apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gold
  project: giri-may
spec:
  base:
    name: default
    version: 2.7.0
  componentsCriticality:
  - name: network-policy
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: golden
  version: versionm1
