apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: krishna-custom
  project: giri-may
spec:
  base:
    name: krishna-gold
    version: version1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
